#!/bin/bash
# ============================================================
# Cloudflare IP 목록 자동 갱신 (cron 주 1회 권장)
# 사용: sudo bash regional-monitor/deploy/cloudflare/update-cf-ips.sh
# cron: 0 4 * * 0 /opt/regionwatch/regional-monitor/deploy/cloudflare/update-cf-ips.sh
# ============================================================
set -euo pipefail

CONF="/etc/nginx/conf.d/cloudflare-realip.conf"
TMP="$(mktemp)"

cat > "${TMP}" <<'HEADER'
# Auto-generated by update-cf-ips.sh — DO NOT EDIT BY HAND
real_ip_header CF-Connecting-IP;
real_ip_recursive on;

HEADER

echo "# IPv4 (https://www.cloudflare.com/ips-v4)" >> "${TMP}"
curl -fsS https://www.cloudflare.com/ips-v4 | while read -r cidr; do
  [ -n "${cidr}" ] && echo "set_real_ip_from ${cidr};" >> "${TMP}"
done

echo "" >> "${TMP}"
echo "# IPv6 (https://www.cloudflare.com/ips-v6)" >> "${TMP}"
curl -fsS https://www.cloudflare.com/ips-v6 | while read -r cidr; do
  [ -n "${cidr}" ] && echo "set_real_ip_from ${cidr};" >> "${TMP}"
done

# 검증 후 적용
if nginx -t -c /etc/nginx/nginx.conf 2>/dev/null; then
  install -m 0644 "${TMP}" "${CONF}"
  if nginx -t; then
    systemctl reload nginx
    echo "✅ Cloudflare IP list updated: $(grep -c set_real_ip_from "${CONF}") entries"
  else
    echo "❌ nginx config test failed after update — rolling back"
    exit 1
  fi
else
  echo "❌ pre-update nginx config invalid — abort"
  exit 1
fi
rm -f "${TMP}"
